spring:
  application:
    name: rest-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_boot_caio?useTimezone=true&serverTimezone=UTC
    username: root
    password: 2022
  jpa:
    hibernate:
      ddl-auto: update #Atraves daqui cria a tabela
    properties:
      hibernate:
    show-sql: false
    open-in-view: false